### PR TITLE
Issue 357 Added confirm dialog on geo coordinate update

### LINKED ISSUE #357: Alert user that they will be overwriting a coordinate position if an observation already exists for a GNSS trait

### PR DESCRIPTION
**Pull request by chaneylc**
Added alert dialog that confirms overwriting geo coord if observation has already been made in GNSS trait.

Fixes #357

### CODE REVIEW

**Comment by chaneylc** [comment]
I added issue #358 fixes

**Comment by trife** [comment]
Let's make the average setting/time persist and 5s be default.

**Comment by trife** [comment]
@chaneylc Can you merge develop back into this?

**Comment by trife** [comment]
@chaneylc Can we move the update warning to before the averaging process?

**Pull request merged**
