### PR TITLE
Added message when a barcode is found in another study.

### PR DESCRIPTION
**Pull request by chaneylc**
issue #184

Original toast still shows that a value wasn't found, then it asks user to switch to the study that has the plot.

Also included an open() call, search activity was still running into closed database exceptions.

### CODE REVIEW

**Comment by trife** [comment]
This is great! Only issue I see is that it currently switches to the other field but doesn't then perform an additional search to move the specific plot that was searched for.

**Comment by trife** [comment]
Receiving the crash below:

```
2022-07-11 01:44:59.501 8958-8958/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fieldbook.tracker, PID: 8958
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=98, result=-1, data=Intent { act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to activity {com.fieldbook.tracker/com.fieldbook.tracker.activities.CollectActivity}: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.fieldbook.tracker/databases/fieldbook.db
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5304)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5343)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.fieldbook.tracker/databases/fieldbook.db
        at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1542)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1485)
        at com.fieldbook.tracker.database.DataHelper.isTableExists(DataHelper.java:2336)
        at com.fieldbook.tracker.database.DataHelper.getAllRangeID(DataHelper.java:1311)
        at com.fieldbook.tracker.activities.CollectActivity$RangeBox.setAllRangeID(CollectActivity.java:2879)
        at com.fieldbook.tracker.activities.CollectActivity.onActivityResult(CollectActivity.java:1810)
        at android.app.Activity.dispatchActivityResult(Activity.java:8382)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5297)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5343) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842)
```

**Comment by trife** [comment]
Can we change the layout of the snackbar to be the same one as the geonav with the icon and color?

**Comment by trife** [comment]
- Can we make the left icon in that snackbar layout a part of the constructor so that we can utilize it for other purposes? Potentially move it to phenolib and include colors as part of the build process as well (or just make an issue for now and do it later when we need it outside of FB). For this specific feature, make the leftmost icon the same that's used for the `Fields` section.
- I'm getting some weird behavior with this feature when geonav is also enabled. The moveToField snackbar displays for a short period but is quickly overwritten with the geonav moveToPlot snackbar. This happens even when on the same plot that is being suggested as the plot to move to.

**Comment by chaneylc** [comment]
Created a new pheno lib issue for your suggestion.

**Pull request merged**
