### PR TITLE
brapi_germ_accession_number

### PR DESCRIPTION
**Pull request by chaneylc**
### Change Type

- [x] **`ADDITION`** (non-breaking change that adds functionality)
- [ ] **`CHANGE`** (fix or feature that alters existing functionality)
- [ ] **`FIX`** (non-breaking change that resolves an issue)
- [ ] **`OTHER`** (use only for changes like tooling, build system, CI, docs, etc.)

### Release Note

```release-note
Accession number now included for germplasm imported via BrAPI
```
___

### Release Type

_For internal use - please leave these unchecked unless you are the one completing the merge._

- [ ] **`MAJOR`**
- [ ] **`MINOR`**
- [x] **`WAIT`** (No immediate release, but the changelog will be still be updated if there is a release note.)

### CODE REVIEW

**Comment by nickpalladino** [comment]
@chaneylc Is this part of the new experimental brapi import that was mentioned in https://github.com/PhenoApps/Field-Book/issues/1055? If so, is the plan to move everything to that? Does it need an equivalent change in the old brapi service code?

**Comment by chaneylc** [comment]
These changes are only for the new brapi import. We can make the changes to the old brapi code if necessary but the idea is to replace it.

**Comment by trife** [comment]
@nickpalladino We're going to try to avoid making too many more updates to the legacy brapi import. The (currently) experimental version should graduate to a release feature before our next minor release (likely before EOY). We're just working on adding a few final touches and allowing some partners to test it out.

**Comment by nickpalladino** [comment]
Thanks for the update. We'll do some testing with the new brapi import code. I'm good with the change just going in the new code since the plan is to switch over to that soon.

**Review by trife — APPROVED** [review]

**Pull request merged**
