### PR TITLE
fixed search box so text entry field is visible

### PR DESCRIPTION
**Pull request by joegage**
## Description

The search feature in Collection had spinners centered in the screen, pushing the text entry field out of view, so it was not possible to search:

image

I modified the box layout by giving the spinners and the text field equal weights. This seems pulls the text field back into visibility. 

**I am not an experienced Android developer, so I don't know if this is the best way to accomplish this. Maybe there is another, preferred way!**

image

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```Fixed missing text entry field in search.

```

### CODE REVIEW

**Comment by trife** [comment]
What device/emulator was showing this behavior? Search is rendering fine on my main device so want to see if this is a device-specific issue.

**Comment by chaneylc** [comment]
Hey @joegage thanks for the PR. Can you give us more detail on what type of device and android os you're using? I'm not able to reproduce this on the main branch with a Pixel 6 API 33 emulator.

**Comment by chaneylc** [comment]
Hey @joegage thanks for the PR, can you share what type of device and android os you're using? I am not able to reproduce this problem on a Pixel 6 API 33 device, thanks.

**Comment by joegage** [comment]
Ah, interesting - we have this issue with our physical devices (Moto Play G, 2021, Android 11) - the search screen looks just like in the emulator screencap above. The emulator I'm using is Pixel 6 API 30, also running Android 11.

**Comment by trife** [comment]
@joegage I'm going to merge this in for now but will hopefully redo search into it's own window at some point in the future. Thanks for the contribution!

@all-contributors add @joegage code

**Review by trife — APPROVED** [review]

**Pull request merged**
