### PR TITLE
Updated default primary/secondary plot values to NA.

### PR DESCRIPTION
**Pull request by chaneylc**
# Description

Some BrAPI endpoints don't use coordinateX or coordinateY in their data. FB now defaults these values to -1.

### CODE REVIEW

**Comment by ctucker3** [comment]
Did you test this? I'm having a hard time setting up a test for this in the test server.

**Comment by ctucker3** [comment]
It might be better if @nahuel-soldevilla were to try this out since he initially reported this and will have a good test case.

**Comment by nahuel-soldevilla** [comment]
I'll take a look today :+1:

**Comment by nahuel-soldevilla** [comment]
I have tested this my local environment, I've manually reverted the workaround in BMS to return the empty coordinates.
With this patch I can import the study ok, but when I go to collect data the app crashes, I can see this in log:
```
  java.lang.RuntimeException: Unable to resume activity {com.fieldbook.tracker/com.fieldbook.tracker.activities.CollectActivity}: android.database.sqlite.SQLiteException: no such column: Row (code 1 SQLITE_ERROR): , while compiling: SELECT `Row`, `Column`, `observationUnitDbId`, `id` FROM ObservationUnitProperty WHERE id = ?
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3784)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.database.sqlite.SQLiteException: no such column: Row (code 1 SQLITE_ERROR): , while compiling: SELECT `Row`, `Column`, `observationUnitDbId`, `id` FROM ObservationUnitProperty WHERE id = ?
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1255)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1126)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1294)
        at com.fieldbook.tracker.database.SqlUtilKt.query(SqlUtil.kt:53)
        at com.fieldbook.tracker.database.SqlUtilKt.query$default(SqlUtil.kt:51)
        at com.fieldbook.tracker.database.dao.ObservationUnitPropertyDao$Companion$getRangeFromId$1.invoke(ObservationUnitPropertyDao.kt:56)
        at com.fieldbook.tracker.database.dao.ObservationUnitPropertyDao$Companion$getRangeFromId$1.invoke(ObservationUnitPropertyDao.kt:50)
        at com.fieldbook.tracker.database.SqlUtilKt.withDatabase(SqlUtil.kt:162)
        at com.fieldbook.tracker.database.dao.ObservationUnitPropertyDao$Companion.getRangeFromId(ObservationUnitPropertyDao.kt:50)
        at com.fieldbook.tracker.database.DataHelper.getRange(DataHelper.java:1392)
        at com.fieldbook.tracker.activities.CollectActivity$RangeBox.reload(CollectActivity.java:1803)
        at com.fieldbook.tracker.activities.CollectActivity.onResume(CollectActivity.java:554)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
```
Sadly we don't have any public BMS server to help with this either, every server has already the workaround to return the default coordinates (even https://brapi.bms-uat-test.net)

Just for curiosity, I've tested to change the fix to use `1` instead of `-1`, but the result is the same:
```kotlin
            val rowid = db.insert(ObservationUnit.tableName, null, contentValuesOf(
                    Study.FK to exp_id,
                    "observation_unit_db_id" to data[uniqueIndex],
                    "primary_id" to if (primaryIndex < 0) 1 else data[primaryIndex],
                    "secondary_id" to if (secondaryIndex < 0) 1 else data[secondaryIndex]))
```

**Comment by trife** [comment]
I thought I had gotten rid of the dependencies of primary/secondary in a much earlier commit. I'll investigate.

**Comment by trife** [comment]
@chaneylc Can we get rid of the dependency for primary/secondary in `ObservationUnitProperty.getRangeFromId( )`?

**Comment by trife** [comment]
@nahuel-soldevilla can you export the database and post the .db file here (or send via email) so we can see how things are being constructed?

**Comment by nahuel-soldevilla** [comment]
I'm having some problems trying to to get the app running now (something with android studio), I'll try again later and send the db via email

**Comment by chaneylc** [comment]
Ok I changed the import process a tad to allow imported plots with no observation unit position data. So these values will default to "NA" when you're traversing your plots in the collect activity. I was able to test this on the brapi test-server.

**Review by nahuel-soldevilla — COMMENTED** [review]
I haven't had time to fully test this yet, though I did test the happy path the other day and it seems to be working ok, I could successfully import the fields and collect data for studies with no coordinates, and then exported that data back.

image (4)

Code looks ok to me though I'm not too familiar with this part.

**Pull request merged**
