### PR TITLE
Inamori branch

### PR DESCRIPTION
**Pull request by m-inamori**
# Description

Added a barcode input toggle on TraitEditorActivity. If the toggle button is set to 'on', the trait layout becomes only a barcode button. And we push the button push, then it enters barcode input mode.
I added 'with_barcode' field to TraitObject, and added it to SQLite database.

Fixes # (issue)

When a Boolean trait editor open and close it without doing anything, an alert box appears.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe any tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [] Test A
- [] Test B

**Test Configuration**:
* Hardware:
* SDK:

# Checklist:

- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to documentation
- [] My changes generate no new warnings

### CODE REVIEW

**Comment by m-inamori** [comment]
I wrote a code for barcode at Cornell. But I was rejected it.
This is second trial.

**Comment by m-inamori** [comment]
I wrote a code for barcode at Cornell. But, it was rejected.
This is second trial.

**Comment by m-inamori** [comment]
I wrote a code for barcode at Cornell. But, it was rejected.
This is second trial.

**Comment by trife** [comment]
Hi @m-inamori , I'm going to review this pull request this week. Thanks for the contribution!

**Comment by BrapiCoordinatorSelby** [comment]
@trife What is the status of this branch? Does it still need reviewing?
At a quick look, it looks like something has gone wrong with @m-inamori git directory. There are a lot of files from `.github` which should have never been committed. We can add a gitignore to remove these files before officially merging the good code.

**Comment by BrapiCoordinatorSelby** [comment]
the m-inamori:inamori-branch branch had committed lots of unnecessary files from the `/.github/` directory. These files should have been ignored. I created a new branch and pull request #141 with this issue resolved. I am closing this pull request without merging.
@trife @m-inamori please see my code review on #141 and merge the code from there.

**Pull request closed without merging**
