### PR TITLE
collect location preference

### PR DESCRIPTION
**Pull request by chaneylc**
issue #170 

manual -> saves location in profile preferences on each phenotype
obs unit -> saves first location per plot, reuses that location for next phenotypes
obs -> saves a new location for each phenotype

External gps is prioritized when geonav is enabled.

### CODE REVIEW

**Comment by trife** [comment]
- Missing `pref_general_location_acquisition_level_entries` and `pref_general_location_acquisition_level_values` arrays

**Comment by trife** [comment]
- Remove location preference from Profile
- Remove manual option from current implementation
- Add 'Field level' option that updates location pref for first observation in a given field
- Add 'Off' option that doesn't collect location
- Rename to 'Automatic location collection'
- Update summaries to accurately reflect options

**Comment by chaneylc** [comment]
I need to double check the profile preference isn't used in other places.

**Comment by trife** [comment]
- Is there currently any way for this to use other GNSS devices other than the internal GPS?

**Comment by chaneylc** [comment]
The external GPS is used when Geonav is enabled.

**Comment by trife** [comment]
@chaneylc this is good to get merged once conflicts are resolved.

**Pull request merged**
