### PR TITLE
Data Grid Update Discussion PR

### LINKED ISSUE #255: Modify datagrid activity to be full screen activity
Utilize code from Intercross wishlist to improve layouts.

### PR DESCRIPTION
**Pull request by chaneylc**
# Description

 This activity is available as an optional toolbar action in the collect activity.
 Toolbar can be activated by selecting Preferences/General/Datagrid
 
 Displays a spreadsheet of plots and trait values.
 Traits are shown as static column headers, while plot ids are shown as static row headers.
 
 Users can click on cell data to navigate to that specific plot/trait in the collect activity.
 When a cell is clicked, the activity finishes and returns an intent with data e.g:
```
 Intent i = Intent()
 i.putExtra("result", plotId)
 i.putExtra("trait", 1) <- actually a trait index s.a 0 -> "height", 1 -> "lodging"
```
Fixes #255 

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have only tested this on emulator with sample data.

### CODE REVIEW

**Comment by chaneylc** [comment]
Should I add a progress bar load while the table is initialized?

**Comment by trife** [comment]
- Progress bar during load would be great. Is there any allowance or possibility of caching the layout to speed up subsequent load times?
- Add toolbar with back button. Ultimately we'll add a heatmap option to this toolbar that shades cells based on values. We can probably delay this for now but we'll eventually need to implement the functions necessary to account for both continuous/discrete values along with any cases where extra characters (or strings) are included in the array (e.g. "NA").
- I think fling scrolling would be advantageous for longer fields.
- I only tested performance on 200 plots x 12 traits. Does performance degrade with large numbers of rows, columns, or either?

**Comment by chaneylc** [comment]
I switched to TableView which seems to perform well for large datasets. Tested on a 100x100 plot study which loaded pretty quickly, there is a slight lag with horizontal scrolling but we might be able to tweak the caching to make it faster. Added a toolbar back button to go back to the collect activity. We should also decide what to do with the other item touch events that are currently unimplemented: 
```kotlin

 override fun onCellDoubleClicked(cellView: RecyclerView.ViewHolder, column: Int, row: Int) {
        TODO("Not yet implemented")
    }

    override fun onCellLongPressed(cellView: RecyclerView.ViewHolder, column: Int, row: Int) {
        TODO("Not yet implemented")
    }

    override fun onColumnHeaderClicked(columnHeaderView: RecyclerView.ViewHolder, column: Int) {
        TODO("Not yet implemented")
    }

    override fun onColumnHeaderDoubleClicked(
        columnHeaderView: RecyclerView.ViewHolder,
        column: Int
    ) {
        TODO("Not yet implemented")
    }

    override fun onColumnHeaderLongPressed(columnHeaderView: RecyclerView.ViewHolder, column: Int) {
        TODO("Not yet implemented")
    }

    override fun onRowHeaderClicked(rowHeaderView: RecyclerView.ViewHolder, row: Int) {
        TODO("Not yet implemented")
    }

    override fun onRowHeaderDoubleClicked(rowHeaderView: RecyclerView.ViewHolder, row: Int) {
        TODO("Not yet implemented")
    }

    override fun onRowHeaderLongPressed(rowHeaderView: RecyclerView.ViewHolder, row: Int) {
        TODO("Not yet implemented")
    }
```

**Comment by trife** [comment]
This looks great!!!

I think for the time being you can just add a return statement to all the unimplemented methods until we get a little more feedback about the feature.

It looks like the header and table rows don't quite line up all the time due to a spacer view in the header. Is this an optional view that needs to be disabled?

**Pull request merged**
