### PR TITLE
changed label/val brapi pref default value from array to string

### LINKED ISSUE #425: [BUG] Supply default value for the 'Value vs. Label Display' preference
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fieldbook.tracker, PID: 13964
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonElement.getAsString()' on a null object reference
        at com.fieldbook.tracker.traits.CategoricalTraitLayout.loadLayout(CategoricalTraitLayout.java:102)
        at com.fieldbook.tracker.activities.CollectActivity$TraitBox$4.onItemSelected(CollectActivity.java:2121)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
        at android.widget.AdapterView.access$300(AdapterView.java:55)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
D/TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=479932992 in 1000ms(Backend next call timestamp 1652237557236). Attempt 1
```

### PR DESCRIPTION
**Pull request by chaneylc**
fixes #425 
xml had an array reference when it should have been a string

### CODE REVIEW

**Comment by trife** [comment]
@chaneylc Setting default via xml doesn't actually work that way. I ran into the same issue with the toolbar icons: https://github.com/PhenoApps/Field-Book/blob/183d269b88843a1e656ddbd3c7a726a0261b608f/app/src/main/java/com/fieldbook/tracker/activities/ConfigActivity.java#L160

**Comment by chaneylc** [comment]
Not sure what the issue was with the toolbar but it is working for me. The original problem was that the default value accessed an array xml definition and not a string value. On my first commit of this PR I fixed that to point to a string, but it was the wrong one, it was Value (entry title) and should have been "value" (entry value), it needs to be a string that exists in the entries defined in the xml. On a fresh install / cleared memory it is correctly defaulting to value in the preferences.

**Comment by trife** [comment]
That still crashes for me from a clean install after importing the alfalfabase backup without manually going into the setting and selecting one of the options. Still works fine after I select one of the options, so the default value isn't getting applied. Have to start from the imported db each time or else it won't be "unset".

```
2022-05-11 17:01:17.141 13567-13567/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fieldbook.tracker, PID: 13567
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonElement.getAsString()' on a null object reference
        at com.fieldbook.tracker.traits.CategoricalTraitLayout.loadLayout(CategoricalTraitLayout.java:102)
        at com.fieldbook.tracker.activities.CollectActivity$TraitBox$4.onItemSelected(CollectActivity.java:2121)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
        at android.widget.AdapterView.access$300(AdapterView.java:55)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by chaneylc** [comment]
Can you post your Settings.xml for me

**Comment by trife** [comment]
After testing, it looks like it's only an issue when importing that old db. Tested from clean install and by upgrading from current Google Play version and it applied the setting as expected.

This probably isn't affecting a lot of people so I'll go ahead and merge.

**Comment by chaneylc** [comment]
Shared preferences are backed up by default, so you might have still had the array reference in your settings, even after reinstalling.

**Pull request merged**
