### PR TITLE
Remove `Output` folder from zip

### PR DESCRIPTION
**Pull request by kamathprasad9**
## Description

Remove the Output folder from the zip and keep all the files and directories in the root of the zip file (#878 )

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated relevant documentation

## Changelog entry

```Modify file zipping```

### CODE REVIEW

**Review by chaneylc — CHANGES_REQUESTED** [review]
This breaks database importing.

```
Unzip exception (Ask Gemini)
                                                                                                    java.io.StreamCorruptedException: invalid stream header: 53514C69
                                                                                                    	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:865)
                                                                                                    	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:356)
                                                                                                    	at com.fieldbook.tracker.utilities.ZipUtil$Companion.unzip(ZipUtil.kt:175)
                                                                                                    	at com.fieldbook.tracker.preferences.DatabasePreferencesFragment$ImportDBTask.doInBackground(DatabasePreferencesFragment.java:182)
                                                                                                    	at com.fieldbook.tracker.preferences.DatabasePreferencesFragment$ImportDBTask.doInBackground(DatabasePreferencesFragment.java:129)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)```

**Review by chaneylc — CHANGES_REQUESTED** [review]
Looks good, couple of things:

1. Selected Field ID preference is not loading after importing a database, this is probably a bug in main but would be good to fix in this PR.

2. Let's go ahead and update backup.db to backup the preferences with the same zip functions. You can find this usage in onPause of CollectActivity.

3. Similarly update the sample.db and preferences file under assets/database to a zip file

**Comment by chaneylc** [comment]
When importing a backup.zip the previously selected field is not selected. Upon investigating further it looks like the backup.zip file's preference file is not being populated correctly.

**Comment by kamathprasad9** [comment]
Thanks @chaneylc for noticing the issue about backup preferences. I also noticed that the sample db was working fine when imported through the dialog that pops up on FB startup, but the CollectActivity page was not being populated properly when the sample db was imported through the settings. Have fixed both of these now

**Review by chaneylc — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
